### ISSUE TITLE
[Continuous Deployment] Document how to use our CLI to deploy from GitHub / GitLab CD

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#2018]
Following the removal of `dpl` mentions in our documentation (#2017), we should document a more generic way to use our CLI and API to deploy to Scalingo from GitHub & GitLab.

Good first step: updating the documentation with a working process, should be enough for now (provide some templates of gitlab-ci.yml, with commands using the CLI/git).

Ideally: we could/should provide templates for GitHub actions/GitLab ci for both deploying an app + creating a review app (we could even publish official GitHub actions for this, on top of our SCM integrations for those who need custom workflows).

**Comment by nclavaud** [comment]
Hi @EtienneM, we are using Github Actions and we would like to remove the SCM integration and setup an additional job in our continuous deployment workflow instead (because of some race condition issues).

Basically, we have 3 options:

1. Deploying with git https://doc.scalingo.com/platform/deployment/deploy-with-git
2. or with the CLI https://doc.scalingo.com/platform/deployment/deploy-from-archive
3. or with the API https://developers.scalingo.com/deployments#trigger-manually-a-deployment-from-a-github-repository

I'm thinking the easiest to integrate in our Github Actions workflow would be option 2 (using the CLI). Should be as easy as:
- [installing Scalingo CLI](https://doc.scalingo.com/platform/cli/start#installation)
- [login with a token](https://doc.scalingo.com/platform/cli/introduction#prerequisites) retrieved from a secret
- [deploy from the archive URL](https://doc.scalingo.com/platform/deployment/deploy-from-archive)

How does it sound? Any other good option we should consider? Or any code example available online that does this already?

**Comment by EtienneM** [comment]
Yes I think that it's a good way to do this using your GitHub Action. We unfortunately don't have any example available for now. But feel free to contact our support team if you need assistance to achieve this, they would happily help you :)

**Comment by nclavaud** [comment]
For the record, I managed to get a working implementation for Github Actions :raised_hands: 
```yaml
# SCALINGO_TOKEN should be defined as a Github Actions secret
# SCALINGO_APP_NAME should be defined as a Github Actions repository variable

  deploy:
    name: Deploy

    # maximum execution time in minutes (before the job gets canceled)
    timeout-minutes: 30

    # only deploy on push events (after pull request is merged)
    if: ${{ github.event_name == 'push' }}

    # wait before tests pass (here, test_suite is another job in the same workflow)
    needs: test_suite

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Scalingo CLI
        run: curl -O https://cli-dl.scalingo.com/install && bash install

      - name: Login
        run: scalingo login --api-token ${{ secrets.SCALINGO_TOKEN }}

      - name: Deploy
        run: |
          git archive --prefix=master/ master > master.tar
          gzip master.tar
          scalingo --app ${{ vars.SCALINGO_APP_NAME }} deploy master.tar.gz ${{ github.sha }}
```
