### ISSUE TITLE
Document Symfony/doctrine parameters to enable TLS

### ISSUE THREAD

**Issue by mcimbaro** [Scalingo/documentation#3103]
Doctrine doesn't support the standard `useSSL=true&verifyServerCertificate=false` parameter on the URL to configure TLS. If nothing is configured, the connection to the DB will fail with one of the following message:

```bash
In ExceptionConverter.php line 101:
                                                                                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'USERNAME'@'192.168.100.3' (using password: YES)  
                                                                                                                                               

In Exception.php line 24:
                                                                                                          
  SQLSTATE[HY000] [1045] Access denied for user 'symfony_tes_5397'@'192.168.100.3' (using password: YES)  
                                                                                                          

In Driver.php line 33:
                                                                                                          
  SQLSTATE[HY000] [1045] Access denied for user 'symfony_tes_5397'@'192.168.100.3' (using password: YES)  
                                                                                                          

dbal:run-sql [--connection CONNECTION] [--depth DEPTH] [--force-fetch] [--] <sql>
```

To enable TLS, we must add the following parameters in the `config/packages/doctrine.yaml` file:
```yaml
options:
  !php/const PDO::MYSQL_ATTR_SSL_CA: '/usr/share/ca-certificates/Scalingo/scalingo-database.pem'
  !php/const PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: true
```

The file looks like:
```yaml
doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        server_version: '8.0.40'

        driver: 'pdo_mysql'
        options:
          !php/const PDO::MYSQL_ATTR_SSL_CA: '/tmp/no'
          !php/const PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: false
```
